FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -y \
    make \
    wget \
    python3-pip \
    awscli && \
    pip3 install --upgrade pip && \
    pip3 install ansible pytest testinfra && \
    curl -sSL https://install.python-poetry.org | python3 - \
    apt-get clean && \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

SHELL ["/bin/bash", "-c"]

ENV TZ=Europe/London

WORKDIR /workspace

CMD [ "bash" ]
