---
- name: Restart_docker
  ansible.builtin.systemd:
     state: restarted
     daemon_reload: true
     name: docker
     enabled: true

- name: Daemon_reload
  ansible.builtin.systemd:
     daemon_reload: true
