---
- name: Start Docker service
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true

- name: Create folder
  ansible.builtin.file:
    path: "{{ deploy_web_app_install_path }}"
    state: directory
    owner: root
    group: root
    mode: '0644'

- name: Copy Dockerfile to EC2 instance
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ deploy_web_app_install_path }}/docker-compose.yml"
    owner: root
    group: root
    mode: '0644'
