---
- name: Start Docker service
  service:
    name: docker
    state: started
    enabled: true

- name: Ensure Docker service is started
  systemd:
    name: docker
    state: started
    enabled: true

- name: Copy Dockerfile to EC2 instance
  ansible.builtin.copy:
    src: ../../docker
    dest: /home/ec2-user/
    owner: ec2-user
    group: ec2-user
    mode: '0644'

- name: Build Docker image
  ansible.builtin.command: docker build -t web_app /home/ec2-user/
  args:
    chdir: /home/ec2-user/

- name: Run Docker container
  community.docker.docker_container:
    name: web_app
    image: web_app
    state: started
    restart_policy: always
    ports:
      - "80:80"
