---
- name: Ensure Docker service is started
  ansible.builtin.systemd:
    name: docker
    state: started
    enabled: true

- name: Log into Github  # noqa: args[module]
  become: true
  community.docker.docker_login:
    registry: ghcr.io
    username: "{{ docker_username }}"
    password: "{{ docker_pass }}"
    reauthorize: true
  tags: ["docker", "redeploy", "always"]

- name: Check Docker Compose stack
  ansible.builtin.shell:
    cmd: "docker compose ps --filter status=running --services"
    chdir: "{{ install_path }}"
  args:
    executable: /bin/bash
  register: stack_state
  changed_when: stack_state.rc !=2
  tags: ["always"]

- name: Start Docker Compose stack if not running
  community.docker.docker_compose_v2:
    project_src: /home/ec2-user/docker-compose.yml
    state: present
  when: not docker_compose_status.changed
