---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-json
      - id: check-toml
      - id: check-yaml
      - id: detect-private-key
      # - id: detect-aws-credentials
  # CICD ####################################################################
  - repo: https://github.com/sirosen/check-jsonschema
    rev: 0.26.1
    hooks:
      - id: check-github-workflows
  # ANSIBLE ####################################################################
  - repo: https://github.com/ansible-community/ansible-lint
    rev: v6.18.0
    hooks:
      - id: ansible-lint
        args: ['-c', '.ci/ansible-lint']
  # PYTHON #####################################################################
  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black
        exclude: files/mods_by_kllw538/
        args: ['--config', './pyproject.toml']
  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        args: ['--config', '.ci/flake8']
  # DOCKER #####################################################################
  - repo: https://github.com/hadolint/hadolint
    rev: v2.12.1-beta
    hooks:
      - id: hadolint-docker
        args: ['-c', '.ci/hadolint.yaml']
  # TERRAFORM ##############################################################
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.88.0
    hooks:
      - id: terraform_fmt
      - id: terraform_validate
      - id: terraform_tflint
      - id: terraform_providers_lock
    # MARKDOWN LINT ##############################################################
  - repo: https://github.com/markdownlint/markdownlint
    rev: v0.12.0
    hooks:
      - id: markdownlint

  # COMMITIZEN #################################################################
  - hooks:
      - id: commitizen
      - id: commitizen-branch
        stages:
          - push
    repo: https://github.com/commitizen-tools/commitizen
    rev: v3.18.4
