---
default_language_version:
  ruby: 2.7.2
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-merge-conflict
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: end-of-file-fixer
      - id: check-json
      - id: check-toml
      - id: check-yaml
      - id: detect-private-key
      - id: mixed-line-ending
      - id: check-case-conflict

# # Add grype hook for Docker image vulnerability scanning
#   - repo: https://github.com/anchore/grype
#     rev: v0.79.3
#     hooks:
#       - id: grype
#         args: [--exit-code 0]

  # CICD ####################################################################
  - repo: https://github.com/sirosen/check-jsonschema
    rev: 0.29.0
    hooks:
      - id: check-github-workflows

  # ANSIBLE  ################################################################
  - repo: https://github.com/ansible/ansible-lint
    rev: v24.7.0
    hooks:
      - id: ansible-lint
        args: ['-c', '.ci/ansible-lint']

  # YAML ####################################################################
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.35.1
    hooks:
      - id: yamllint
        args: ['-c=.ci/yamllint']

  # TERRAFORM ##############################################################
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.92.0
    hooks:
      - id: terraform_fmt
      - id: terraform_tflint
    # - id: terraform_validate

   # Docker hooks
  - repo: https://github.com/IamTheFij/docker-pre-commit
    rev: v3.0.1
    hooks:
      - id: docker-compose-check

  - repo: https://github.com/pryorda/dockerfilelint-precommit-hooks
    rev: v0.1.0
    hooks:
      - id: dockerfilelint

# MARKDOWN LINT ##############################################################
  - repo: https://github.com/markdownlint/markdownlint
    rev: v0.12.0
    hooks:
      - id: markdownlint

  # COMMITIZEN #################################################################
  - hooks:
      - id: commitizen
      - id: commitizen-branch
        stages:
          - push
    repo: https://github.com/commitizen-tools/commitizen
    rev: v3.28.0
