---
- name: Install yum-utils
  ansible.builtin.dnf:
    name: yum-utils
    state: present

- name: Add Docker CE repository
  ansible.builtin.command: yum-config-manager --add-repo https://download.docker.com/linux/rhel/docker-ce.repo
  register: my_output
  changed_when: my_output.rc != 0

- name: Install Docker packages
  ansible.builtin.dnf:
    name: "{{ install_docker_redhat_packages }}"
    state: present

- name: Start and enable Docker service
  ansible.builtin.systemd:
    name: docker
    state: started
    enabled: true

- name: Create docker group if it does not exist
  ansible.builtin.group:
    name: docker
    state: present

- name: Add ec2-user to the docker group
  ansible.builtin.user:
    name: ec2-user
    groups: docker
    append: true
