---
- name: Install Nginx
  ansible.builtin.dnf:
    name: nginx
    state: present
    update_cache: true
  tags: ["nginx"]

- name: Create Nginx configuration file
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: /etc/nginx/conf.d/default.conf
    owner: root
    group: root
    mode: '0644'
  register: nginx_conf
  notify: Restart_nginx
  tags: ["nginx"]

- name: Ensure Nginx is running and enabled
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: true
  tags: ["nginx"]
