---
name: Terraform Destroy

on: workflow_dispatch # yamllint disable-line rule:truthy

jobs:
  terraform-destroy:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: 'eu-central-1'
    permissions:
      contents: read

    steps:
      - name: Install make and tfmask
        run: |
          sudo apt-get update
          sudo apt-get install -y make wget
          sudo wget https://github.com/cloudposse/tfmask/releases/download/0.7.0/tfmask_linux_amd64 -O /usr/bin/tfmask
          sudo chmod 755 /usr/bin/tfmask

      - name: Checkout code
        uses: actions/checkout@v3.6.0

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.1.7"

      - name: Terraform Init
        id: init
        run: make init
        working-directory: deployment/terraform

      - name: Show Destroy plan
        run: terraform plan -destroy
        continue-on-error: true

      - name: Terraform Destroy
        id: destroy
        run: make destroy
        working-directory: deployment/terraform
