---
name: Terraform Destroy

on: # yamllint disable-line rule:truthy
  workflow_dispatch:
    inputs:
      job_environment:
        type: choice
        description: 'Job environment prod or dev'
        required: true
        default: 'dev'
        options:
          - dev
          - prod
jobs:
  terraform-destroy:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: 'eu-central-1'
    permissions:
      contents: read
      packages: write

    steps:
      - name: Install make and tfmask
        run: |
          sudo apt-get update
          sudo apt-get install -y make wget
          sudo wget https://github.com/cloudposse/tfmask/releases/download/0.7.0/tfmask_linux_amd64 -O /usr/bin/tfmask
          sudo chmod 755 /usr/bin/tfmask
          sudo apt-get install -y awscli

      - name: Checkout code
        uses: actions/checkout@v3.6.0

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        id: init
        run: make init
        working-directory: deployment/terraform

      - name: Select workspace
        run: make workspace
        working-directory: deployment/terraform

      - name: Show Destroy plan
        id: plan
        run: make plan
        continue-on-error: true
        working-directory: deployment/terraform

      - name: Terraform Destroy
        id: destroy
        run: make destroy
        working-directory: deployment/terraform
