---
name: Pre-commit Lint Check

# yamllint disable-line rule:truthy
on:
    # yamllint disable-line rule:empty-values
  push:
    branches-ignore:
      - '**'
      - '!master'
      - '!main'
      - '!refs/pull/*'

jobs:
  pre-commit:
    runs-on:
      - self-hosted
    container:
      image: ghcr.io/banigoden/web_app-ghcr:latest
      credentials:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
      env:
        registry-username: ${{ secrets.DOCKER_USERNAME }}
        registry-password: ${{ secrets.DOCKER_PASSWORD }}
    steps:
      - name: Checkout current repo
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Run pre-commit
        uses: pre-commit/action@v3.0.0
        with:
          extra_args: --all-files -c .ci/pre-commit-config.yaml

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit
          pre-commit install

      - name: Run linters
        run: pre-commit run --all-files
