---
name: Pre-commit Lint Check

# yamllint disable-line rule:truthy
on:
    # yamllint disable-line rule:empty-values
  push:
    branches-ignore:
      - '**'
      - '!master'
      - '!main'
      - '!refs/pull/*'

jobs:
  pre-commit:
    runs-on:
      - ubuntu-latest
    steps:
      - name: Checkout current repo
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Run linter
        run: |
          pip install poetry
          poetry run pre-commit install
          poetry run pre-commit --all-files
